<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AAD-W17Q1DRL3" failures="3" tests="3" name="APIM_OAuth2" time="213.812" errors="0" timestamp="15 Dec 2022 18:02:34 GMT">
  <testcase classname="com.informatica.tests.PoliciesAuthorizationTest" name="ValdiateCreateOAuth2Client" time="60.623">
    <failure type="java.lang.AssertionError" message="Exception while validating Create OAuth2 Client">
      <![CDATA[java.lang.AssertionError: Exception while validating Create OAuth2 Client
at com.informatica.tests.PoliciesAuthorizationTest.ValdiateCreateOAuth2Client(PoliciesAuthorizationTest.java:91)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- ValdiateCreateOAuth2Client -->
  <testcase classname="com.informatica.tests.PoliciesAuthorizationTest" name="ValdiateEditOAuth2Client" time="62.132">
    <failure type="java.lang.AssertionError" message="Exception while validating Create OAuth2 Client">
      <![CDATA[java.lang.AssertionError: Exception while validating Create OAuth2 Client
at com.informatica.tests.PoliciesAuthorizationTest.ValdiateEditOAuth2Client(PoliciesAuthorizationTest.java:137)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- ValdiateEditOAuth2Client -->
  <testcase classname="com.informatica.tests.PoliciesAuthorizationTest" name="ValdiateDeleteOAuth2Client" time="60.033">
    <failure type="java.lang.AssertionError" message="Exception while validating Deleting OAuth2 Client">
      <![CDATA[java.lang.AssertionError: Exception while validating Deleting OAuth2 Client
at com.informatica.tests.PoliciesAuthorizationTest.ValdiateDeleteOAuth2Client(PoliciesAuthorizationTest.java:166)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- ValdiateDeleteOAuth2Client -->
</testsuite> <!-- APIM_OAuth2 -->
